// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" className="" suppressHydrationWarning>
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 dark:bg-slate-950`}>
//           {children}
//       </body>
//     </html>
//   );
// }


{/* SEO */}


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Spotify Stats | Your Music Trends & Listening Insights",
  description:
    "Track your Spotify listening habits, top artists, tracks, and genres. See your music trends and share your Spotify profile stats with friends.",
  metadataBase: new URL("https://yourdomain.com"), // change to your domain
  openGraph: {
    title: "Spotify Stats | Your Music Trends & Listening Insights",
    description:
      "Discover your top artists, tracks, and genres on Spotify. View personalized listening statistics and share them with friends.",
    url: "https://yourdomain.com",
    siteName: "Spotify Stats",
    images: [
      {
        url: "/og-image.png", // add an Open Graph image
        width: 1200,
        height: 630,
        alt: "Spotify Stats Dashboard Preview",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Spotify Stats | Your Music Trends & Listening Insights",
    description:
      "Analyze your Spotify listening history and share your stats.",
    images: ["/og-image.png"],
    creator: "@yourTwitterHandle",
  },
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="theme-color" content="#1DB954" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 dark:bg-slate-950`}
      >
        {children}
      </body>
    </html>
  );
}
